// EnumIterator.py AUTOGENERATED FILE. ** DO NOT EDIT ** Run "python2 Run.py"
#ifndef _ExampleHeader2Enum_H_
#define _ExampleHeader2Enum_H_

#include <vector>
#include <string>
#include "ExampleHeader2.h"

#endif
